### ISSUE TITLE
Problems installing trimethyl

### ISSUE THREAD

**Issue by nubu** [CaffeinaLab/Ti.Sharer#1]
Hey,

your widget seems to be really great- but i can't get trimethyl to run correctly.

I've used "npm install trimethyl" to install it to my project dir, but it still throws a warning, that it is not available.

Am i missing something?

Best, Nico

**Comment by kopiro** [comment]
I'll push a new version on NPM with this fix.
You can easily bypass this warning by defining `Ti.Trimethyl = true`

Otherwise, it's just a warning:

```
if (Ti.Trimethyl == null) Ti.API.warn(WNAME + ': This widget require Trimethyl to be installed (https://github.com/CaffeinaLab/Trimethyl)');
```
